# Generated by Django 5.0.14 on 2026-04-07 00:19

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True, default='', verbose_name='Popis')),
                ('color', models.CharField(default='#00ff41', max_length=7, verbose_name='Barva')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skupina',
                'verbose_name_plural': 'Skupiny',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('color', models.CharField(default='#00ff41', max_length=7, verbose_name='Barva')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Ikona')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Štítek',
                'verbose_name_plural': 'Štítky',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Prostřední jméno')),
                ('nickname', models.CharField(blank=True, default='', max_length=100, verbose_name='Přezdívka')),
                ('gender', models.CharField(choices=[('M', 'Muž'), ('F', 'Žena'), ('O', 'Jiné'), ('U', 'Neuvedeno')], default='U', max_length=1, verbose_name='Pohlaví')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Datum úmrtí')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.photo_path, verbose_name='Fotografie')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biografie')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Poznámky')),
                ('address_street', models.CharField(blank=True, default='', max_length=200, verbose_name='Ulice')),
                ('address_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Město')),
                ('address_zip', models.CharField(blank=True, default='', max_length=20, verbose_name='PSČ')),
                ('address_country', models.CharField(blank=True, default='', max_length=100, verbose_name='Země')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Firma')),
                ('job_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Pozice')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Oblíbený')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='members', to='core.group', verbose_name='Skupiny')),
                ('tags', models.ManyToManyField(blank=True, related_name='persons', to='core.tag', verbose_name='Štítky')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('doc_type', models.CharField(choices=[('photo', 'Fotografie'), ('id_card', 'Občanský průkaz'), ('passport', 'Pas'), ('driver_lic', 'Řidičský průkaz'), ('contract', 'Smlouva'), ('cert', 'Certifikát'), ('letter', 'Dopis'), ('invoice', 'Faktura'), ('note', 'Poznámka'), ('other', 'Jiný')], default='other', max_length=20, verbose_name='Typ')),
                ('file', models.FileField(upload_to=core.models.doc_path, verbose_name='Soubor')),
                ('description', models.TextField(blank=True, default='', verbose_name='Popis')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.person')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumenty',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Telefon'), ('mobile', 'Mobil'), ('web', 'Web'), ('social', 'Sociální síť'), ('msg', 'Messenger'), ('other', 'Jiný')], default='other', max_length=10, verbose_name='Typ')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='Popis')),
                ('value', models.CharField(max_length=500, verbose_name='Hodnota')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primární')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.person')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakty',
                'ordering': ['-is_primary', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True, default='', verbose_name='Popis')),
                ('color', models.CharField(default='#00ff41', max_length=7, verbose_name='Barva')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník')),
            ],
            options={
                'verbose_name': 'Pracovní prostor',
                'verbose_name_plural': 'Pracovní prostory',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='person',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models._gen_code, max_length=20, unique=True, verbose_name='Kód')),
                ('role', models.CharField(choices=[('owner', 'Vlastník'), ('editor', 'Editor'), ('viewer', 'Čtenář')], default='editor', max_length=10, verbose_name='Role')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Max použití')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Použito')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Platnost do')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Pozvánka',
                'verbose_name_plural': 'Pozvánky',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.person')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('parent', 'Rodič'), ('child', 'Dítě'), ('sibling', 'Sourozenec'), ('spouse', 'Manžel/ka'), ('partner', 'Partner/ka'), ('grandparent', 'Prarodič'), ('grandchild', 'Vnuk/vnučka'), ('uncle_aunt', 'Strýc/teta'), ('cousin', 'Bratranec/sestřenice'), ('friend', 'Přítel/kyně'), ('bestfriend', 'Nejlepší přítel/kyně'), ('colleague', 'Kolega/yně'), ('boss', 'Nadřízený/á'), ('subordinate', 'Podřízený/á'), ('classmate', 'Spolužák/čka'), ('neighbor', 'Soused/ka'), ('acquaintance', 'Známý/á'), ('enemy', 'Nepřítel/kyně'), ('mentor', 'Mentor/ka'), ('mentee', 'Mentee'), ('other', 'Jiný vztah')], default='other', max_length=20, verbose_name='Typ vztahu')),
                ('description', models.TextField(blank=True, default='', verbose_name='Popis')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Začátek')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Konec')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rels_from', to='core.person')),
                ('person_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rels_to', to='core.person')),
            ],
            options={
                'verbose_name': 'Vztah',
                'verbose_name_plural': 'Vztahy',
                'unique_together': {('person_from', 'person_to', 'relation_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('workspace', 'name')},
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Vlastník'), ('editor', 'Editor'), ('viewer', 'Čtenář')], default='editor', max_length=10, verbose_name='Role')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Členství',
                'verbose_name_plural': 'Členství',
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
